setup/urls.py
from django.contrib import admin
from django.urls import include, path

from saf.views import home
from saf.views import safListarView  #Class Based Views
from saf.views import safCriarView
from saf.views import safAtualizarView
from saf.views import safDeletarView

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", home),
    #path("", safListar),
    path("", safListarView.as_view(template_name="saf/saflistar.html"), name='saf_listar'),
    path("criar", safCriarView.as_view(), name='saf_criar'),     
    # pk é o parametro da tarefa que será atualizada
    path("atualizar/<int:pk>", safAtualizarView.as_view(), name='saf_atualizar'),
    # url de debug do django debug toolbars
    path("__debug__/", include("debug_toolbar.urls")),
    path("excluir/<int:pk>", safDeletarView.as_view(), name='saf_excluir'),

    
]

saf/models.py
from django.db import models


# Create your models here.


#criando a tabela Todo
class saf(models.Model):
    titulo = models.CharField(max_length=150, null=False, blank=False)
    dtCriacao = models.DateTimeField(auto_now_add=True, null=False, blank=False)
    dtFinalizado = models.DateTimeField(null=True, blank=True)

saf/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import saf
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.urls import reverse_lazy

# Create your views here.


def home(request):
    # return HttpResponse('<h1>view Home</h1>')
    return render(request, "saf\home.html")


# def safListar(request):
#     # tarefas = [{
#     #     'id':'1',
#     #     'Tarefa':'comprar fraldas'
#     # }]


#     tarefas = saf.objects.all()  # busca todos os dados do banco


#     return render(request, "saf/saflistar.html",{'tarefas':tarefas})

class safListarView(ListView):
    model = saf #classe deve usar o modelo saf (.\saf\models.py)
class safCriarView(CreateView):
    model = saf
    fields = ["titulo","dtFinalizado"]  # Uma lista de campos que o usuario pode alterar
    success_url = reverse_lazy('saf_listar')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = 'Adicionar Tarefa'
        return context


class safAtualizarView(UpdateView):
    model = saf
    fields = ["titulo","dtFinalizado"]  # Uma lista de campos que o usuario pode alterar
    success_url = reverse_lazy('saf_listar')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = 'Atualizar Tarefa'
        return context
class safDeletarView(DeleteView):
    model = saf
    success_url = reverse_lazy('saf_listar')
    template_name = "saf/saf_confirm_delete.html"

saf/templates/padrao.html
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
      {% block titulo %}


      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  </head>
  <body>
    {% comment %}inicio da barra de navegação{% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">TODO</a>
      </div>
    </nav>
    {% comment %}Fim da barra de navegação{% endcomment %}


    <main class="container">
      <p class="text-start fs-4 fw-bold">
        {% block subtitulo %}


        {% endblock %}
      </p>
      {% block conteudo %}


      {% endblock %}
        {% comment %}inicio do modal de confirmação de exclusão{% endcomment %}
    <div id="modalDeletar" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Confirmação de exclusao de tarefa</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
              <p>Deseja excluir a tarefa abaixo</p>
              <p>ID: {{saf.id}}</p>
              <p>Descrição:{{saf.titulo}}</p>
            </div>
            <div class="modal-footer">
              <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" data-dismiss="modal">Confirmar</button>
                <button type="button" onclick="window.location.href='{% url 'saf_listar' %}'" class="btn btn-primary">Cancelar</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% comment %}fim do modal de confirmação de exclusão{% endcomment %}
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

saf/templates/saf/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="pt-BR">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Sfernandes </h1>
    <h1>Family SAF </h1>
</body>
</html>

saf/templates/saf/saf_confirm_delete.html
{% extends 'padrao.html' %}


{% block titulo %}
  Exclusao de tarefas
{% endblock %}


{% block subtitulo %}
  Exclusao de tarefas
{% endblock %}


{% block conteudo %}
  {% comment %}inicio do modal de confirmação de exclusão{% endcomment %}
  <script>
    window.addEventListener("load", (event) => {
       // Exibir o modal ao carregar a página
      $('#modalDeletar').modal('show')
    });
  </script>
  {% comment %}fim do modal de confirmação de exclusão{% endcomment %}
{% endblock %}

saf/templates/saf/saf_form.html
{% extends 'padrao.html' %}
{% load crispy_forms_tags %}


{% block titulo %}
  {{ titulo_pagina }}
{% endblock %}


{% comment %}o sistema de template do django não permite usar o mesmo bloco duas vezes{% endcomment %}
{% block subtitulo %}
  {{ titulo_pagina }}
{% endblock %}


{% block conteudo %}
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="ENVIAR" />
    <button type="button" 
            onclick="window.location.href='{% url 'saf_listar' %}'" 
            class="btn btn-warning">Cancelar</button>
  </form>
{% endblock %}

saf/templates/saf/saflistar.html
{% extends 'padrao.html' %}

{% block titulo %}
  Listagem de tarefas
{% endblock %}

{% block subtitulo %}
  Listagem de tarefas
{% endblock %}

{% block conteudo %}
  {% comment %}Inicio botao de criacao de tarefa{% endcomment %}
  <a href="{% url 'saf_criar' %}" type="button" class="btn btn-success">Nova Tarefa</a>
  {% comment %}Fim botao de criacao de tarefa{% endcomment %}

  {% comment %}Inicio da tabela{% endcomment %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titulo</th>
        <th scope="col">Criação</th>
        <th scope="col">Finalizacao</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for tarefa in saf_list %}
        <tr>
          <th scope="row">{{ tarefa.id }}</th>
          <td>{{ tarefa.titulo }}</td>
          <td>{{ tarefa.dtCriacao|date:'SHORT_DATE_FORMAT' }}</td>
          <td>{{ tarefa.dtFinalizacao|date:'SHORT_DATE_FORMAT'|default:'-' }}</td>

          {% comment %}botoes de acoes{% endcomment %}
          <td>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
              <button type="button" onclick="window.location.href='{% url 'saf_atualizar' pk=tarefa.pk %}'" class="btn btn-warning">Editar</button>

              <button type="button" onclick="window.location.href='{% url 'saf_excluir' pk=tarefa.pk %}'" class="btn btn-danger">Excluir</button>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% comment %}fim da tabela{% endcomment %}
{% endblock %}